use_frameworks!

target 'Ramda_Example' do
  pod 'Ramda', :path => '../'
end

target 'Ramda_Tests' do
  inherit! :search_paths
  pod 'Ramda', :path => '../'
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
