language: objective-c
osx_image: xcode8

podfile: Example/Podfile

install:
  - ./swift-lint.sh

script:
- gem install xcpretty
- swiftlint
- cd Example
- pod install
- cd ..
- xcodebuild -workspace Example/Ramda.xcworkspace -scheme Ramda_Tests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'  ONLY_ACTIVE_ARCH=YES clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Ramda'

notifications:
  email:
    - tyronemichael@gmail.com
    - justin.guedes@gmail.com
