language: swift
osx_image: xcode10.1

podfile: Example/Podfile

script:
- gem install xcpretty
- swiftlint
- cd Example
- pod install
- cd ..
- xcodebuild -workspace Example/Ramda.xcworkspace -scheme Ramda_Tests -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1'  ONLY_ACTIVE_ARCH=YES clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Ramda'

notifications:
  email:
    - tyronemichael@gmail.com
    - justin.guedes@gmail.com

before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
