language: objective-c
osx_image: xcode7.3

script: 
- xctool -project Example/Ramda.xcodeproj -scheme Ramda_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO clean build test
